# Generated by Django 2.2.4 on 2019-08-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionimage',
            name='nama',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
