# Generated by Django 2.2.4 on 2019-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_predictionimage_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='upload/')),
                ('model_weights', models.FileField(upload_to='upload/')),
            ],
        ),
    ]
